imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@CityFinderBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    cache:
        default_memcached_provider: "memcached://localhost:11212"
        pools:
            app.cache.products:
                adapter: cache.adapter.memcached
                public: true
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer:
        enabled: true
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }



# FOS REST
fos_rest:
    routing_loader:
        include_format: false #permet d'avoir des routes ne prenant pas de multiples type (json xml...)
    view:
        view_response_listener: true #permet lors du retour d'une méthode du controller avec un array, de créer une réponse
    format_listener:
        rules:
            - { path: '^/search-commune', priorities: ['html'], fallback_format: 'html' } #paramètres par défaut de l'API
            - { path: '^/', priorities: ['json'], fallback_format: 'json' } #paramètres par défaut de l'API
    # permet de décoder le contenu json transmis dans le body d'une requête
    body_listener:
        enabled: true

    routing_loader:
        include_format: false

    serializer:
        serialize_null:  true


# neo4j
neo4j:
  profiling:
    enabled: true
  connections:
    default:
      scheme: bolt # default (must be either "http" or "bolt")
      host: localhost # default
      port: 7687 # optional, will be set to the proper driver's default port if not provided
      username: neo4j # default
      password: 0123@abcd # default
  clients:
    default:
      connections: [default]
    foobar: ~ # foobar client will have the "default" connection
  entity_managers:
    default:
      client: default # defaults to "default"
      cache_dir: "%kernel.cache_dir%/neo4j" # defaults to system cache
