CityFinderBundle\Entity\AuthTokens:
    exclusion_policy: none
    accessor_order: custom
    custom_accessor_order: [value, createdAt, userId]
    properties:
        userId:
            groups: ['user', 'module', 'auth-token', 'users']
        value:
            groups: ['user', 'module', 'auth-token', 'users']
        createdAt:
            groups: ['user', 'module', 'auth-token', 'users']
